# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
name: Update Haxe Eval Debugger

on:
  schedule:
    # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
    - cron: '0 16 * * 3' # Wednesday at 16:00
  workflow_dispatch:
    # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch


defaults:
  run:
    shell: bash


jobs:
  ###########################################################
  update-eval-debugger:
  ###########################################################
    runs-on: ubuntu-latest

    steps:
    - name: "Show: GitHub context"
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: printf '%s' "$GITHUB_CONTEXT" | python -m json.tool


    - name: "Show: environment variables"
      run: env | sort


    - name: Git Checkout
      uses: actions/checkout@v4  # https://github.com/actions/checkout


    - name: Build Haxe Eval Debugger
      id: update
      run: |
        set -euo pipefail

        set -x
        git clone --depth 1 https://github.com/vshaxe/eval-debugger

        cd eval-debugger

        npm install
        npx lix run vshaxe-build -v -t eval-debugger

        ls bin

        cp -f bin/index.js ../plugin/src/main/resources/langsrv/haxe-eval-debugger.min.js
        cd ..
        set +x

        updates=$(git status --porcelain plugin/src/main/resources/langsrv/haxe-eval-debugger.min.js)
        if [[ -z $updates ]]; then
          echo "updates=" >> "$GITHUB_OUTPUT"
        else
          # https://github.com/orgs/community/discussions/26288#discussioncomment-3876281
          delimiter="$(openssl rand -hex 8)"
          echo "updates<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "${updates}" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"
        fi


    - name: Generate GitHub Access Token
      uses: tibdex/github-app-token@v2  # https://github.com/tibdex/github-app-token
      id: generate_token
      if: "${{ steps.update.outputs.updates != '' }}"
      # see https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens
      with:
        # see https://github.com/organizations/haxe4e/settings/apps/haxe4e-tu
        app_id: ${{ secrets.HAXE4E_TU_APP_ID }}
        private_key: ${{ secrets.HAXE4E_TU_PRIVATE_KEY }}


    - name: Create PR
      id: create-pr
      uses: peter-evans/create-pull-request@v7  # https://github.com/peter-evans/create-pull-request
      if: "${{ steps.update.outputs.updates != '' }}"
      with:
        title: "fix(deps): Update Haxe Eval Debugger"
        author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
        committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
        commit-message: "fix(deps): Update Haxe Eval Debugger"
        body: ${{ steps.update.outputs.updates }}
        add-paths: plugin/src/main/resources/langsrv/haxe-eval-debugger.min.js
        branch: dependencies/haxe_eval_debugger
        delete-branch: true
        token: ${{ steps.generate_token.outputs.token }}
